FROM ubuntu:15.10
WORKDIR /root

RUN apt-get update \
&& export DEBIAN_FRONTEND=noninteractive \
&& apt-get upgrade -y \
&& apt-get install -y tightvncserver vncviewer twm xterm x11-xserver-utils firefox

ADD xstartup /root/.vnc/
ENV USER root
